name: Test Lowercase Conversion

on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'Enter a value'
        required: true

jobs:
  convert_input_to_lowercase:
    runs-on: ubuntu-latest
    steps:
      - name: Convert input to lowercase
        id: convert
        run: |
          lowercase_value=$(echo '${{ github.event.inputs.myInput }}' | tr '[:upper:]' '[:lower:]')
          echo "lowercase_value=$lowercase_value" >> $GITHUB_ENV
        
      - name: Use the lowercase value
        run: echo "Lowercase value is: ${{ env.lowercase_value }}"
